# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crosszone_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import online_tracking_results_pb2 as online__tracking__results__pb2
import event_pb2 as event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='crosszone_service.proto',
  package='tracking_pipeline.online',
  syntax='proto3',
  serialized_options=b'Z\006./.gen',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63rosszone_service.proto\x12\x18tracking_pipeline.online\x1a\x0c\x63ommon.proto\x1a\x1donline_tracking_results.proto\x1a\x0b\x65vent.proto\"\xb4\x03\n\x0fZoneDataRequest\x12\x36\n\x0cinput_tracks\x18\x01 \x03(\x0b\x32 .tracking_pipeline.online.Tracks\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12H\n\x08\x63id_info\x18\x04 \x03(\x0b\x32\x36.tracking_pipeline.online.ZoneDataRequest.CidInfoEntry\x12N\n\x0bnpp_results\x18\x05 \x03(\x0b\x32\x39.tracking_pipeline.online.ZoneDataRequest.NppResultsEntry\x12\x0c\n\x04zone\x18\x06 \x01(\t\x1aJ\n\x0c\x43idInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.tracking_pipeline.CidInfo:\x02\x38\x01\x1aO\n\x0fNppResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.tracking_pipeline.NppResult:\x02\x38\x01\"\xd1\x03\n\x10ZoneDataResponse\x12P\n\x0c\x63id_end_time\x18\x01 \x03(\x0b\x32:.tracking_pipeline.online.ZoneDataResponse.CidEndTimeEntry\x12\x35\n\x06\x65vents\x18\x02 \x03(\x0b\x32%.tracking_pipeline.online.OnlineEvent\x12@\n\x0cregion_stats\x18\x03 \x03(\x0b\x32*.tracking_pipeline.online.RegionStatistics\x12:\n\x0ctrajectories\x18\x04 \x03(\x0b\x32$.tracking_pipeline.online.Trajectory\x12@\n\x0csynced_stats\x18\x05 \x03(\x0b\x32*.tracking_pipeline.online.RegionStatistics\x12\x41\n\x13synced_trajactories\x18\x06 \x03(\x0b\x32$.tracking_pipeline.online.Trajectory\x1a\x31\n\x0f\x43idEndTimeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x32{\n\x10\x43rossZoneService\x12g\n\x0eInsertZoneData\x12).tracking_pipeline.online.ZoneDataRequest\x1a*.tracking_pipeline.online.ZoneDataResponseB\x08Z\x06./.genb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,online__tracking__results__pb2.DESCRIPTOR,event__pb2.DESCRIPTOR,])




_ZONEDATAREQUEST_CIDINFOENTRY = _descriptor.Descriptor(
  name='CidInfoEntry',
  full_name='tracking_pipeline.online.ZoneDataRequest.CidInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tracking_pipeline.online.ZoneDataRequest.CidInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tracking_pipeline.online.ZoneDataRequest.CidInfoEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=467,
)

_ZONEDATAREQUEST_NPPRESULTSENTRY = _descriptor.Descriptor(
  name='NppResultsEntry',
  full_name='tracking_pipeline.online.ZoneDataRequest.NppResultsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tracking_pipeline.online.ZoneDataRequest.NppResultsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tracking_pipeline.online.ZoneDataRequest.NppResultsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=548,
)

_ZONEDATAREQUEST = _descriptor.Descriptor(
  name='ZoneDataRequest',
  full_name='tracking_pipeline.online.ZoneDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_tracks', full_name='tracking_pipeline.online.ZoneDataRequest.input_tracks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='tracking_pipeline.online.ZoneDataRequest.start_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='tracking_pipeline.online.ZoneDataRequest.end_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cid_info', full_name='tracking_pipeline.online.ZoneDataRequest.cid_info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='npp_results', full_name='tracking_pipeline.online.ZoneDataRequest.npp_results', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zone', full_name='tracking_pipeline.online.ZoneDataRequest.zone', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ZONEDATAREQUEST_CIDINFOENTRY, _ZONEDATAREQUEST_NPPRESULTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=548,
)


_ZONEDATARESPONSE_CIDENDTIMEENTRY = _descriptor.Descriptor(
  name='CidEndTimeEntry',
  full_name='tracking_pipeline.online.ZoneDataResponse.CidEndTimeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tracking_pipeline.online.ZoneDataResponse.CidEndTimeEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tracking_pipeline.online.ZoneDataResponse.CidEndTimeEntry.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=967,
  serialized_end=1016,
)

_ZONEDATARESPONSE = _descriptor.Descriptor(
  name='ZoneDataResponse',
  full_name='tracking_pipeline.online.ZoneDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid_end_time', full_name='tracking_pipeline.online.ZoneDataResponse.cid_end_time', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='tracking_pipeline.online.ZoneDataResponse.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_stats', full_name='tracking_pipeline.online.ZoneDataResponse.region_stats', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trajectories', full_name='tracking_pipeline.online.ZoneDataResponse.trajectories', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='synced_stats', full_name='tracking_pipeline.online.ZoneDataResponse.synced_stats', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='synced_trajactories', full_name='tracking_pipeline.online.ZoneDataResponse.synced_trajactories', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ZONEDATARESPONSE_CIDENDTIMEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=1016,
)

_ZONEDATAREQUEST_CIDINFOENTRY.fields_by_name['value'].message_type = common__pb2._CIDINFO
_ZONEDATAREQUEST_CIDINFOENTRY.containing_type = _ZONEDATAREQUEST
_ZONEDATAREQUEST_NPPRESULTSENTRY.fields_by_name['value'].message_type = common__pb2._NPPRESULT
_ZONEDATAREQUEST_NPPRESULTSENTRY.containing_type = _ZONEDATAREQUEST
_ZONEDATAREQUEST.fields_by_name['input_tracks'].message_type = online__tracking__results__pb2._TRACKS
_ZONEDATAREQUEST.fields_by_name['cid_info'].message_type = _ZONEDATAREQUEST_CIDINFOENTRY
_ZONEDATAREQUEST.fields_by_name['npp_results'].message_type = _ZONEDATAREQUEST_NPPRESULTSENTRY
_ZONEDATARESPONSE_CIDENDTIMEENTRY.containing_type = _ZONEDATARESPONSE
_ZONEDATARESPONSE.fields_by_name['cid_end_time'].message_type = _ZONEDATARESPONSE_CIDENDTIMEENTRY
_ZONEDATARESPONSE.fields_by_name['events'].message_type = event__pb2._ONLINEEVENT
_ZONEDATARESPONSE.fields_by_name['region_stats'].message_type = event__pb2._REGIONSTATISTICS
_ZONEDATARESPONSE.fields_by_name['trajectories'].message_type = event__pb2._TRAJECTORY
_ZONEDATARESPONSE.fields_by_name['synced_stats'].message_type = event__pb2._REGIONSTATISTICS
_ZONEDATARESPONSE.fields_by_name['synced_trajactories'].message_type = event__pb2._TRAJECTORY
DESCRIPTOR.message_types_by_name['ZoneDataRequest'] = _ZONEDATAREQUEST
DESCRIPTOR.message_types_by_name['ZoneDataResponse'] = _ZONEDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZoneDataRequest = _reflection.GeneratedProtocolMessageType('ZoneDataRequest', (_message.Message,), {

  'CidInfoEntry' : _reflection.GeneratedProtocolMessageType('CidInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _ZONEDATAREQUEST_CIDINFOENTRY,
    '__module__' : 'crosszone_service_pb2'
    # @@protoc_insertion_point(class_scope:tracking_pipeline.online.ZoneDataRequest.CidInfoEntry)
    })
  ,

  'NppResultsEntry' : _reflection.GeneratedProtocolMessageType('NppResultsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ZONEDATAREQUEST_NPPRESULTSENTRY,
    '__module__' : 'crosszone_service_pb2'
    # @@protoc_insertion_point(class_scope:tracking_pipeline.online.ZoneDataRequest.NppResultsEntry)
    })
  ,
  'DESCRIPTOR' : _ZONEDATAREQUEST,
  '__module__' : 'crosszone_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.ZoneDataRequest)
  })
_sym_db.RegisterMessage(ZoneDataRequest)
_sym_db.RegisterMessage(ZoneDataRequest.CidInfoEntry)
_sym_db.RegisterMessage(ZoneDataRequest.NppResultsEntry)

ZoneDataResponse = _reflection.GeneratedProtocolMessageType('ZoneDataResponse', (_message.Message,), {

  'CidEndTimeEntry' : _reflection.GeneratedProtocolMessageType('CidEndTimeEntry', (_message.Message,), {
    'DESCRIPTOR' : _ZONEDATARESPONSE_CIDENDTIMEENTRY,
    '__module__' : 'crosszone_service_pb2'
    # @@protoc_insertion_point(class_scope:tracking_pipeline.online.ZoneDataResponse.CidEndTimeEntry)
    })
  ,
  'DESCRIPTOR' : _ZONEDATARESPONSE,
  '__module__' : 'crosszone_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.ZoneDataResponse)
  })
_sym_db.RegisterMessage(ZoneDataResponse)
_sym_db.RegisterMessage(ZoneDataResponse.CidEndTimeEntry)


DESCRIPTOR._options = None
_ZONEDATAREQUEST_CIDINFOENTRY._options = None
_ZONEDATAREQUEST_NPPRESULTSENTRY._options = None
_ZONEDATARESPONSE_CIDENDTIMEENTRY._options = None

_CROSSZONESERVICE = _descriptor.ServiceDescriptor(
  name='CrossZoneService',
  full_name='tracking_pipeline.online.CrossZoneService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=1018,
  serialized_end=1141,
  methods=[
  _descriptor.MethodDescriptor(
    name='InsertZoneData',
    full_name='tracking_pipeline.online.CrossZoneService.InsertZoneData',
    index=0,
    containing_service=None,
    input_type=_ZONEDATAREQUEST,
    output_type=_ZONEDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CROSSZONESERVICE)

DESCRIPTOR.services_by_name['CrossZoneService'] = _CROSSZONESERVICE

# @@protoc_insertion_point(module_scope)
