# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import disinfection_event_pb2 as disinfection__event__pb2
import track_pipeline_service_pb2 as track__pipeline__service__pb2


class DisinfectionEventStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.process = channel.unary_unary(
                '/tracking_pipeline.online.DisinfectionEvent/process',
                request_serializer=track__pipeline__service__pb2.tracks_cameraevents.SerializeToString,
                response_deserializer=track__pipeline__service__pb2.PiplineResponse.FromString,
                )
        self.push_event = channel.unary_unary(
                '/tracking_pipeline.online.DisinfectionEvent/push_event',
                request_serializer=disinfection__event__pb2.EventResult.SerializeToString,
                response_deserializer=track__pipeline__service__pb2.PiplineResponse.FromString,
                )


class DisinfectionEventServicer(object):
    """Missing associated documentation comment in .proto file."""

    def process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def push_event(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisinfectionEventServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'process': grpc.unary_unary_rpc_method_handler(
                    servicer.process,
                    request_deserializer=track__pipeline__service__pb2.tracks_cameraevents.FromString,
                    response_serializer=track__pipeline__service__pb2.PiplineResponse.SerializeToString,
            ),
            'push_event': grpc.unary_unary_rpc_method_handler(
                    servicer.push_event,
                    request_deserializer=disinfection__event__pb2.EventResult.FromString,
                    response_serializer=track__pipeline__service__pb2.PiplineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking_pipeline.online.DisinfectionEvent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DisinfectionEvent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tracking_pipeline.online.DisinfectionEvent/process',
            track__pipeline__service__pb2.tracks_cameraevents.SerializeToString,
            track__pipeline__service__pb2.PiplineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def push_event(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tracking_pipeline.online.DisinfectionEvent/push_event',
            disinfection__event__pb2.EventResult.SerializeToString,
            track__pipeline__service__pb2.PiplineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
