# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_detection_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import online_event_detection_pb2 as online__event__detection__pb2
import online_tracking_results_pb2 as online__tracking__results__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_detection_service.proto',
  package='tracking_pipeline.online',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1d\x65vent_detection_service.proto\x12\x18tracking_pipeline.online\x1a\x1conline_event_detection.proto\x1a\x1donline_tracking_results.proto\"e\n\x16\x45ventDetectionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12=\n\rcamera_events\x18\x02 \x01(\x0b\x32&.tracking_pipeline.online.CameraEvents2\xe7\x01\n\x15\x45ventDetectionService\x12\x66\n\x0e\x45ventDetection\x12 .tracking_pipeline.online.Tracks\x1a\x30.tracking_pipeline.online.EventDetectionResponse\"\x00\x12\x66\n\x0eStateDetection\x12 .tracking_pipeline.online.Tracks\x1a\x30.tracking_pipeline.online.EventDetectionResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[online__event__detection__pb2.DESCRIPTOR,online__tracking__results__pb2.DESCRIPTOR,])




_EVENTDETECTIONRESPONSE = _descriptor.Descriptor(
  name='EventDetectionResponse',
  full_name='tracking_pipeline.online.EventDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='tracking_pipeline.online.EventDetectionResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_events', full_name='tracking_pipeline.online.EventDetectionResponse.camera_events', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=221,
)

_EVENTDETECTIONRESPONSE.fields_by_name['camera_events'].message_type = online__event__detection__pb2._CAMERAEVENTS
DESCRIPTOR.message_types_by_name['EventDetectionResponse'] = _EVENTDETECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventDetectionResponse = _reflection.GeneratedProtocolMessageType('EventDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVENTDETECTIONRESPONSE,
  '__module__' : 'event_detection_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.EventDetectionResponse)
  })
_sym_db.RegisterMessage(EventDetectionResponse)



_EVENTDETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='EventDetectionService',
  full_name='tracking_pipeline.online.EventDetectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=224,
  serialized_end=455,
  methods=[
  _descriptor.MethodDescriptor(
    name='EventDetection',
    full_name='tracking_pipeline.online.EventDetectionService.EventDetection',
    index=0,
    containing_service=None,
    input_type=online__tracking__results__pb2._TRACKS,
    output_type=_EVENTDETECTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StateDetection',
    full_name='tracking_pipeline.online.EventDetectionService.StateDetection',
    index=1,
    containing_service=None,
    input_type=online__tracking__results__pb2._TRACKS,
    output_type=_EVENTDETECTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTDETECTIONSERVICE)

DESCRIPTOR.services_by_name['EventDetectionService'] = _EVENTDETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
