# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evt_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import online_tracking_results_pb2 as online__tracking__results__pb2
import event_pb2 as event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65vt_service.proto\x12\x18tracking_pipeline.online\x1a\x0c\x63ommon.proto\x1a\x1donline_tracking_results.proto\x1a\x0b\x65vent.proto\"\xac\x03\n\x11\x45vtProcessRequest\x12\x36\n\x0cinput_tracks\x18\x01 \x03(\x0b\x32 .tracking_pipeline.online.Tracks\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12J\n\x08\x63id_info\x18\x04 \x03(\x0b\x32\x38.tracking_pipeline.online.EvtProcessRequest.CidInfoEntry\x12P\n\x0bnpp_results\x18\x05 \x03(\x0b\x32;.tracking_pipeline.online.EvtProcessRequest.NppResultsEntry\x1aJ\n\x0c\x43idInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.tracking_pipeline.CidInfo:\x02\x38\x01\x1aO\n\x0fNppResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.tracking_pipeline.NppResult:\x02\x38\x01\"\xd5\x03\n\x12\x45vtProcessResponse\x12R\n\x0c\x63id_end_time\x18\x01 \x03(\x0b\x32<.tracking_pipeline.online.EvtProcessResponse.CidEndTimeEntry\x12\x35\n\x06\x65vents\x18\x02 \x03(\x0b\x32%.tracking_pipeline.online.OnlineEvent\x12@\n\x0cregion_stats\x18\x03 \x03(\x0b\x32*.tracking_pipeline.online.RegionStatistics\x12:\n\x0ctrajectories\x18\x04 \x03(\x0b\x32$.tracking_pipeline.online.Trajectory\x12@\n\x0csynced_stats\x18\x05 \x03(\x0b\x32*.tracking_pipeline.online.RegionStatistics\x12\x41\n\x13synced_trajactories\x18\x06 \x03(\x0b\x32$.tracking_pipeline.online.Trajectory\x1a\x31\n\x0f\x43idEndTimeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x32u\n\nEvtService\x12g\n\nEvtProcess\x12+.tracking_pipeline.online.EvtProcessRequest\x1a,.tracking_pipeline.online.EvtProcessResponseB\x08Z\x06./.genb\x06proto3')



_EVTPROCESSREQUEST = DESCRIPTOR.message_types_by_name['EvtProcessRequest']
_EVTPROCESSREQUEST_CIDINFOENTRY = _EVTPROCESSREQUEST.nested_types_by_name['CidInfoEntry']
_EVTPROCESSREQUEST_NPPRESULTSENTRY = _EVTPROCESSREQUEST.nested_types_by_name['NppResultsEntry']
_EVTPROCESSRESPONSE = DESCRIPTOR.message_types_by_name['EvtProcessResponse']
_EVTPROCESSRESPONSE_CIDENDTIMEENTRY = _EVTPROCESSRESPONSE.nested_types_by_name['CidEndTimeEntry']
EvtProcessRequest = _reflection.GeneratedProtocolMessageType('EvtProcessRequest', (_message.Message,), {

  'CidInfoEntry' : _reflection.GeneratedProtocolMessageType('CidInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVTPROCESSREQUEST_CIDINFOENTRY,
    '__module__' : 'evt_service_pb2'
    # @@protoc_insertion_point(class_scope:tracking_pipeline.online.EvtProcessRequest.CidInfoEntry)
    })
  ,

  'NppResultsEntry' : _reflection.GeneratedProtocolMessageType('NppResultsEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVTPROCESSREQUEST_NPPRESULTSENTRY,
    '__module__' : 'evt_service_pb2'
    # @@protoc_insertion_point(class_scope:tracking_pipeline.online.EvtProcessRequest.NppResultsEntry)
    })
  ,
  'DESCRIPTOR' : _EVTPROCESSREQUEST,
  '__module__' : 'evt_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.EvtProcessRequest)
  })
_sym_db.RegisterMessage(EvtProcessRequest)
_sym_db.RegisterMessage(EvtProcessRequest.CidInfoEntry)
_sym_db.RegisterMessage(EvtProcessRequest.NppResultsEntry)

EvtProcessResponse = _reflection.GeneratedProtocolMessageType('EvtProcessResponse', (_message.Message,), {

  'CidEndTimeEntry' : _reflection.GeneratedProtocolMessageType('CidEndTimeEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVTPROCESSRESPONSE_CIDENDTIMEENTRY,
    '__module__' : 'evt_service_pb2'
    # @@protoc_insertion_point(class_scope:tracking_pipeline.online.EvtProcessResponse.CidEndTimeEntry)
    })
  ,
  'DESCRIPTOR' : _EVTPROCESSRESPONSE,
  '__module__' : 'evt_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.EvtProcessResponse)
  })
_sym_db.RegisterMessage(EvtProcessResponse)
_sym_db.RegisterMessage(EvtProcessResponse.CidEndTimeEntry)

_EVTSERVICE = DESCRIPTOR.services_by_name['EvtService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./.gen'
  _EVTPROCESSREQUEST_CIDINFOENTRY._options = None
  _EVTPROCESSREQUEST_CIDINFOENTRY._serialized_options = b'8\001'
  _EVTPROCESSREQUEST_NPPRESULTSENTRY._options = None
  _EVTPROCESSREQUEST_NPPRESULTSENTRY._serialized_options = b'8\001'
  _EVTPROCESSRESPONSE_CIDENDTIMEENTRY._options = None
  _EVTPROCESSRESPONSE_CIDENDTIMEENTRY._serialized_options = b'8\001'
  _EVTPROCESSREQUEST._serialized_start=106
  _EVTPROCESSREQUEST._serialized_end=534
  _EVTPROCESSREQUEST_CIDINFOENTRY._serialized_start=379
  _EVTPROCESSREQUEST_CIDINFOENTRY._serialized_end=453
  _EVTPROCESSREQUEST_NPPRESULTSENTRY._serialized_start=455
  _EVTPROCESSREQUEST_NPPRESULTSENTRY._serialized_end=534
  _EVTPROCESSRESPONSE._serialized_start=537
  _EVTPROCESSRESPONSE._serialized_end=1006
  _EVTPROCESSRESPONSE_CIDENDTIMEENTRY._serialized_start=957
  _EVTPROCESSRESPONSE_CIDENDTIMEENTRY._serialized_end=1006
  _EVTSERVICE._serialized_start=1008
  _EVTSERVICE._serialized_end=1125
# @@protoc_insertion_point(module_scope)
