# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fdp_proto_face_id_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fdp_proto_face_id_info.proto',
  package='face_pipeline.face_id_info',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x66\x64p_proto_face_id_info.proto\x12\x1a\x66\x61\x63\x65_pipeline.face_id_info\"\x8f\x02\n\x05\x46\x61\x63\x65s\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x38\n\nface_infos\x18\x02 \x03(\x0b\x32$.face_pipeline.face_id_info.FaceInfo\x12\x1c\n\x14\x66\x61\x63\x65_feature_version\x18\x03 \x01(\t\x12\"\n\x1a\x61ppearance_feature_version\x18\x04 \x01(\t\x12\x1c\n\x14\x61ppearance_model_url\x18\x05 \x01(\t\x12\x18\n\x10tracking_version\x18\x06 \x01(\t\x12\x12\n\nstart_date\x18\x07 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x08 \x01(\t\x12\x1b\n\x13\x63ustomer_city_store\x18\t \x01(\t\"\xbe\x01\n\x08\x46\x61\x63\x65Info\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x12\n\nvideo_name\x18\x04 \x01(\t\x12\x17\n\x0fstart_time_msec\x18\x05 \x01(\x04\x12\x15\n\rend_time_msec\x18\x06 \x01(\x04\x12\x14\n\x0c\x66\x61\x63\x65_quality\x18\x07 \x01(\x02\x12\x0e\n\x06gender\x18\x08 \x01(\x05\x12\x0b\n\x03\x61ge\x18\t \x01(\x02\x12\x0b\n\x03pid\x18\n \x01(\tb\x06proto3')
)




_FACES = _descriptor.Descriptor(
  name='Faces',
  full_name='face_pipeline.face_id_info.Faces',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='face_pipeline.face_id_info.Faces.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_infos', full_name='face_pipeline.face_id_info.Faces.face_infos', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_feature_version', full_name='face_pipeline.face_id_info.Faces.face_feature_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='appearance_feature_version', full_name='face_pipeline.face_id_info.Faces.appearance_feature_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='appearance_model_url', full_name='face_pipeline.face_id_info.Faces.appearance_model_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracking_version', full_name='face_pipeline.face_id_info.Faces.tracking_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='face_pipeline.face_id_info.Faces.start_date', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='face_pipeline.face_id_info.Faces.end_date', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_city_store', full_name='face_pipeline.face_id_info.Faces.customer_city_store', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=332,
)


_FACEINFO = _descriptor.Descriptor(
  name='FaceInfo',
  full_name='face_pipeline.face_id_info.FaceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_id', full_name='face_pipeline.face_id_info.FaceInfo.face_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='face_pipeline.face_id_info.FaceInfo.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='face_pipeline.face_id_info.FaceInfo.channel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_name', full_name='face_pipeline.face_id_info.FaceInfo.video_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time_msec', full_name='face_pipeline.face_id_info.FaceInfo.start_time_msec', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time_msec', full_name='face_pipeline.face_id_info.FaceInfo.end_time_msec', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_quality', full_name='face_pipeline.face_id_info.FaceInfo.face_quality', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='face_pipeline.face_id_info.FaceInfo.gender', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='face_pipeline.face_id_info.FaceInfo.age', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='face_pipeline.face_id_info.FaceInfo.pid', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=525,
)

_FACES.fields_by_name['face_infos'].message_type = _FACEINFO
DESCRIPTOR.message_types_by_name['Faces'] = _FACES
DESCRIPTOR.message_types_by_name['FaceInfo'] = _FACEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Faces = _reflection.GeneratedProtocolMessageType('Faces', (_message.Message,), {
  'DESCRIPTOR' : _FACES,
  '__module__' : 'fdp_proto_face_id_info_pb2'
  # @@protoc_insertion_point(class_scope:face_pipeline.face_id_info.Faces)
  })
_sym_db.RegisterMessage(Faces)

FaceInfo = _reflection.GeneratedProtocolMessageType('FaceInfo', (_message.Message,), {
  'DESCRIPTOR' : _FACEINFO,
  '__module__' : 'fdp_proto_face_id_info_pb2'
  # @@protoc_insertion_point(class_scope:face_pipeline.face_id_info.FaceInfo)
  })
_sym_db.RegisterMessage(FaceInfo)


# @@protoc_insertion_point(module_scope)
