# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fdp_proto_feature_list.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fdp_proto_feature_list.proto',
  package='face_pipeline.feature_list',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x66\x64p_proto_feature_list.proto\x12\x1a\x66\x61\x63\x65_pipeline.feature_list\"*\n\rFeatureVector\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x66\x65\x61ts\x18\x02 \x03(\x02\"\xd7\x01\n\x0b\x46\x65\x61tureList\x12\x1d\n\x15\x66\x65\x61ture_model_version\x18\x01 \x01(\t\x12\x1b\n\x13\x63ustomer_city_store\x18\x02 \x01(\t\x12\x42\n\x0f\x66\x65\x61ture_vectors\x18\x03 \x03(\x0b\x32).face_pipeline.feature_list.FeatureVector\x12\x19\n\x11\x66\x65\x61ture_model_url\x18\x04 \x01(\t\x12\x15\n\rfeature_count\x18\x05 \x01(\x04\x12\x16\n\x0e\x66\x65\x61ture_length\x18\x06 \x01(\x04\x62\x06proto3')
)




_FEATUREVECTOR = _descriptor.Descriptor(
  name='FeatureVector',
  full_name='face_pipeline.feature_list.FeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='face_pipeline.feature_list.FeatureVector.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feats', full_name='face_pipeline.feature_list.FeatureVector.feats', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=102,
)


_FEATURELIST = _descriptor.Descriptor(
  name='FeatureList',
  full_name='face_pipeline.feature_list.FeatureList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_model_version', full_name='face_pipeline.feature_list.FeatureList.feature_model_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_city_store', full_name='face_pipeline.feature_list.FeatureList.customer_city_store', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_vectors', full_name='face_pipeline.feature_list.FeatureList.feature_vectors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_model_url', full_name='face_pipeline.feature_list.FeatureList.feature_model_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_count', full_name='face_pipeline.feature_list.FeatureList.feature_count', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_length', full_name='face_pipeline.feature_list.FeatureList.feature_length', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=320,
)

_FEATURELIST.fields_by_name['feature_vectors'].message_type = _FEATUREVECTOR
DESCRIPTOR.message_types_by_name['FeatureVector'] = _FEATUREVECTOR
DESCRIPTOR.message_types_by_name['FeatureList'] = _FEATURELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureVector = _reflection.GeneratedProtocolMessageType('FeatureVector', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREVECTOR,
  '__module__' : 'fdp_proto_feature_list_pb2'
  # @@protoc_insertion_point(class_scope:face_pipeline.feature_list.FeatureVector)
  })
_sym_db.RegisterMessage(FeatureVector)

FeatureList = _reflection.GeneratedProtocolMessageType('FeatureList', (_message.Message,), {
  'DESCRIPTOR' : _FEATURELIST,
  '__module__' : 'fdp_proto_feature_list_pb2'
  # @@protoc_insertion_point(class_scope:face_pipeline.feature_list.FeatureList)
  })
_sym_db.RegisterMessage(FeatureList)


# @@protoc_insertion_point(module_scope)
