# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import track_pipeline_service_pb2 as track__pipeline__service__pb2
import realtime_meta_data_pb2 as realtime__meta__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13generic_event.proto\x12\x18tracking_pipeline.online\x1a\x1ctrack_pipeline_service.proto\x1a\x18realtime_meta_data.proto2g\n\x0cGenericEvent\x12W\n\npush_event\x12\x1c.Realtime.Meta.RealtimeReply\x1a).tracking_pipeline.online.PiplineResponse\"\x00\x62\x06proto3')



_GENERICEVENT = DESCRIPTOR.services_by_name['GenericEvent']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERICEVENT._serialized_start=105
  _GENERICEVENT._serialized_end=208
# @@protoc_insertion_point(module_scope)
