# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import realtime_meta_data_pb2 as realtime__meta__data__pb2
import track_pipeline_service_pb2 as track__pipeline__service__pb2


class GenericEventStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.push_event = channel.unary_unary(
                '/tracking_pipeline.online.GenericEvent/push_event',
                request_serializer=realtime__meta__data__pb2.RealtimeReply.SerializeToString,
                response_deserializer=track__pipeline__service__pb2.PiplineResponse.FromString,
                )


class GenericEventServicer(object):
    """Missing associated documentation comment in .proto file."""

    def push_event(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenericEventServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'push_event': grpc.unary_unary_rpc_method_handler(
                    servicer.push_event,
                    request_deserializer=realtime__meta__data__pb2.RealtimeReply.FromString,
                    response_serializer=track__pipeline__service__pb2.PiplineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking_pipeline.online.GenericEvent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenericEvent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def push_event(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tracking_pipeline.online.GenericEvent/push_event',
            realtime__meta__data__pb2.RealtimeReply.SerializeToString,
            track__pipeline__service__pb2.PiplineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
