# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: godview_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import online_tracking_results_pb2 as online__tracking__results__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='godview_service.proto',
  package='tracking_pipeline.online',
  syntax='proto3',
  serialized_options=_b('Z\006./.gen'),
  serialized_pb=_b('\n\x15godview_service.proto\x12\x18tracking_pipeline.online\x1a\x1donline_tracking_results.proto\"\x15\n\x06Status\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x81\x01\n\x13LocalizationRequest\x12\x30\n\x06tracks\x18\x01 \x01(\x0b\x32 .tracking_pipeline.online.Tracks\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12\x12\n\nchannel_id\x18\x04 \x01(\t\"&\n\x14LocalizationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2t\n\x07Godview\x12i\n\x08Localize\x12-.tracking_pipeline.online.LocalizationRequest\x1a..tracking_pipeline.online.LocalizationResponseB\x08Z\x06./.genb\x06proto3')
  ,
  dependencies=[online__tracking__results__pb2.DESCRIPTOR,])




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='tracking_pipeline.online.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='tracking_pipeline.online.Status.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=103,
)


_LOCALIZATIONREQUEST = _descriptor.Descriptor(
  name='LocalizationRequest',
  full_name='tracking_pipeline.online.LocalizationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='tracking_pipeline.online.LocalizationRequest.tracks', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='tracking_pipeline.online.LocalizationRequest.start_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='tracking_pipeline.online.LocalizationRequest.end_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='tracking_pipeline.online.LocalizationRequest.channel_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=235,
)


_LOCALIZATIONRESPONSE = _descriptor.Descriptor(
  name='LocalizationResponse',
  full_name='tracking_pipeline.online.LocalizationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tracking_pipeline.online.LocalizationResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=275,
)

_LOCALIZATIONREQUEST.fields_by_name['tracks'].message_type = online__tracking__results__pb2._TRACKS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['LocalizationRequest'] = _LOCALIZATIONREQUEST
DESCRIPTOR.message_types_by_name['LocalizationResponse'] = _LOCALIZATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'godview_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.Status)
  })
_sym_db.RegisterMessage(Status)

LocalizationRequest = _reflection.GeneratedProtocolMessageType('LocalizationRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCALIZATIONREQUEST,
  '__module__' : 'godview_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.LocalizationRequest)
  })
_sym_db.RegisterMessage(LocalizationRequest)

LocalizationResponse = _reflection.GeneratedProtocolMessageType('LocalizationResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCALIZATIONRESPONSE,
  '__module__' : 'godview_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.LocalizationResponse)
  })
_sym_db.RegisterMessage(LocalizationResponse)


DESCRIPTOR._options = None

_GODVIEW = _descriptor.ServiceDescriptor(
  name='Godview',
  full_name='tracking_pipeline.online.Godview',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=277,
  serialized_end=393,
  methods=[
  _descriptor.MethodDescriptor(
    name='Localize',
    full_name='tracking_pipeline.online.Godview.Localize',
    index=0,
    containing_service=None,
    input_type=_LOCALIZATIONREQUEST,
    output_type=_LOCALIZATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GODVIEW)

DESCRIPTOR.services_by_name['Godview'] = _GODVIEW

# @@protoc_insertion_point(module_scope)
