# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import godview_service_pb2 as godview__service__pb2


class GodviewStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Localize = channel.unary_unary(
        '/tracking_pipeline.online.Godview/Localize',
        request_serializer=godview__service__pb2.LocalizationRequest.SerializeToString,
        response_deserializer=godview__service__pb2.LocalizationResponse.FromString,
        )


class GodviewServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Localize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GodviewServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Localize': grpc.unary_unary_rpc_method_handler(
          servicer.Localize,
          request_deserializer=godview__service__pb2.LocalizationRequest.FromString,
          response_serializer=godview__service__pb2.LocalizationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tracking_pipeline.online.Godview', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
