# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: human_tracking_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import detection_results_pb2 as detection__results__pb2
import tracking_results_pb2 as tracking__results__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='human_tracking_service.proto',
  package='tracking_pipeline.offline',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1chuman_tracking_service.proto\x12\x19tracking_pipeline.offline\x1a\x0c\x63ommon.proto\x1a\x17\x64\x65tection_results.proto\x1a\x16tracking_results.proto\"c\n\x15HumanTrackingRequests\x12J\n\x11tracking_requests\x18\x01 \x03(\x0b\x32/.tracking_pipeline.offline.HumanTrackingRequest\"d\n\x16HumanTrackingResponses\x12J\n\x10tracking_results\x18\x01 \x03(\x0b\x32\x30.tracking_pipeline.offline.HumanTrackingResponse\"\xf9\x01\n\x14HumanTrackingRequest\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\r\x12\x31\n\x04\x64\x65ts\x18\x02 \x01(\x0b\x32#.tracking_pipeline.DetectionResults\x12\x37\n\x08\x61pp_feat\x18\x03 \x01(\x0b\x32%.tracking_pipeline.AppearanceFeatures\x12\x38\n\tface_feat\x18\x04 \x01(\x0b\x32%.tracking_pipeline.AppearanceFeatures\x12\x13\n\x0b\x66rame_width\x18\x05 \x01(\r\x12\x14\n\x0c\x66rame_height\x18\x06 \x01(\r\"f\n\x15HumanTrackingResponse\x12;\n\x07results\x18\x01 \x01(\x0b\x32*.tracking_pipeline.offline.TrackingResults\x12\x10\n\x08run_time\x18\x02 \x01(\x02\x32\x82\x01\n\x14HumanTrackingService\x12j\n\x05Track\x12/.tracking_pipeline.offline.HumanTrackingRequest\x1a\x30.tracking_pipeline.offline.HumanTrackingResponseb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,detection__results__pb2.DESCRIPTOR,tracking__results__pb2.DESCRIPTOR,])




_HUMANTRACKINGREQUESTS = _descriptor.Descriptor(
  name='HumanTrackingRequests',
  full_name='tracking_pipeline.offline.HumanTrackingRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracking_requests', full_name='tracking_pipeline.offline.HumanTrackingRequests.tracking_requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=221,
)


_HUMANTRACKINGRESPONSES = _descriptor.Descriptor(
  name='HumanTrackingResponses',
  full_name='tracking_pipeline.offline.HumanTrackingResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracking_results', full_name='tracking_pipeline.offline.HumanTrackingResponses.tracking_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=323,
)


_HUMANTRACKINGREQUEST = _descriptor.Descriptor(
  name='HumanTrackingRequest',
  full_name='tracking_pipeline.offline.HumanTrackingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='tracking_pipeline.offline.HumanTrackingRequest.frame_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dets', full_name='tracking_pipeline.offline.HumanTrackingRequest.dets', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_feat', full_name='tracking_pipeline.offline.HumanTrackingRequest.app_feat', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_feat', full_name='tracking_pipeline.offline.HumanTrackingRequest.face_feat', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_width', full_name='tracking_pipeline.offline.HumanTrackingRequest.frame_width', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_height', full_name='tracking_pipeline.offline.HumanTrackingRequest.frame_height', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=575,
)


_HUMANTRACKINGRESPONSE = _descriptor.Descriptor(
  name='HumanTrackingResponse',
  full_name='tracking_pipeline.offline.HumanTrackingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='tracking_pipeline.offline.HumanTrackingResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='run_time', full_name='tracking_pipeline.offline.HumanTrackingResponse.run_time', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=679,
)

_HUMANTRACKINGREQUESTS.fields_by_name['tracking_requests'].message_type = _HUMANTRACKINGREQUEST
_HUMANTRACKINGRESPONSES.fields_by_name['tracking_results'].message_type = _HUMANTRACKINGRESPONSE
_HUMANTRACKINGREQUEST.fields_by_name['dets'].message_type = detection__results__pb2._DETECTIONRESULTS
_HUMANTRACKINGREQUEST.fields_by_name['app_feat'].message_type = common__pb2._APPEARANCEFEATURES
_HUMANTRACKINGREQUEST.fields_by_name['face_feat'].message_type = common__pb2._APPEARANCEFEATURES
_HUMANTRACKINGRESPONSE.fields_by_name['results'].message_type = tracking__results__pb2._TRACKINGRESULTS
DESCRIPTOR.message_types_by_name['HumanTrackingRequests'] = _HUMANTRACKINGREQUESTS
DESCRIPTOR.message_types_by_name['HumanTrackingResponses'] = _HUMANTRACKINGRESPONSES
DESCRIPTOR.message_types_by_name['HumanTrackingRequest'] = _HUMANTRACKINGREQUEST
DESCRIPTOR.message_types_by_name['HumanTrackingResponse'] = _HUMANTRACKINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HumanTrackingRequests = _reflection.GeneratedProtocolMessageType('HumanTrackingRequests', (_message.Message,), {
  'DESCRIPTOR' : _HUMANTRACKINGREQUESTS,
  '__module__' : 'human_tracking_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.offline.HumanTrackingRequests)
  })
_sym_db.RegisterMessage(HumanTrackingRequests)

HumanTrackingResponses = _reflection.GeneratedProtocolMessageType('HumanTrackingResponses', (_message.Message,), {
  'DESCRIPTOR' : _HUMANTRACKINGRESPONSES,
  '__module__' : 'human_tracking_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.offline.HumanTrackingResponses)
  })
_sym_db.RegisterMessage(HumanTrackingResponses)

HumanTrackingRequest = _reflection.GeneratedProtocolMessageType('HumanTrackingRequest', (_message.Message,), {
  'DESCRIPTOR' : _HUMANTRACKINGREQUEST,
  '__module__' : 'human_tracking_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.offline.HumanTrackingRequest)
  })
_sym_db.RegisterMessage(HumanTrackingRequest)

HumanTrackingResponse = _reflection.GeneratedProtocolMessageType('HumanTrackingResponse', (_message.Message,), {
  'DESCRIPTOR' : _HUMANTRACKINGRESPONSE,
  '__module__' : 'human_tracking_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.offline.HumanTrackingResponse)
  })
_sym_db.RegisterMessage(HumanTrackingResponse)



_HUMANTRACKINGSERVICE = _descriptor.ServiceDescriptor(
  name='HumanTrackingService',
  full_name='tracking_pipeline.offline.HumanTrackingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=682,
  serialized_end=812,
  methods=[
  _descriptor.MethodDescriptor(
    name='Track',
    full_name='tracking_pipeline.offline.HumanTrackingService.Track',
    index=0,
    containing_service=None,
    input_type=_HUMANTRACKINGREQUEST,
    output_type=_HUMANTRACKINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HUMANTRACKINGSERVICE)

DESCRIPTOR.services_by_name['HumanTrackingService'] = _HUMANTRACKINGSERVICE

# @@protoc_insertion_point(module_scope)
