# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import face_box_pb2 as face__box__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pipeline_data.proto',
  package='tracking_pipeline',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13pipeline_data.proto\x12\x11tracking_pipeline\x1a\x0e\x66\x61\x63\x65_box.proto\":\n\x0cPB_FaceBoxes\x12*\n\x03\x62ox\x18\x01 \x03(\x0b\x32\x1d.tracking_pipeline.PB_FaceBox\"W\n\x0fPB_PipelineData\x12\x33\n\nface_boxes\x18\x01 \x01(\x0b\x32\x1f.tracking_pipeline.PB_FaceBoxes\x12\x0f\n\x07version\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[face__box__pb2.DESCRIPTOR,])




_PB_FACEBOXES = _descriptor.Descriptor(
  name='PB_FaceBoxes',
  full_name='tracking_pipeline.PB_FaceBoxes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='tracking_pipeline.PB_FaceBoxes.box', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=116,
)


_PB_PIPELINEDATA = _descriptor.Descriptor(
  name='PB_PipelineData',
  full_name='tracking_pipeline.PB_PipelineData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_boxes', full_name='tracking_pipeline.PB_PipelineData.face_boxes', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='tracking_pipeline.PB_PipelineData.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=205,
)

_PB_FACEBOXES.fields_by_name['box'].message_type = face__box__pb2._PB_FACEBOX
_PB_PIPELINEDATA.fields_by_name['face_boxes'].message_type = _PB_FACEBOXES
DESCRIPTOR.message_types_by_name['PB_FaceBoxes'] = _PB_FACEBOXES
DESCRIPTOR.message_types_by_name['PB_PipelineData'] = _PB_PIPELINEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_FaceBoxes = _reflection.GeneratedProtocolMessageType('PB_FaceBoxes', (_message.Message,), {
  'DESCRIPTOR' : _PB_FACEBOXES,
  '__module__' : 'pipeline_data_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.PB_FaceBoxes)
  })
_sym_db.RegisterMessage(PB_FaceBoxes)

PB_PipelineData = _reflection.GeneratedProtocolMessageType('PB_PipelineData', (_message.Message,), {
  'DESCRIPTOR' : _PB_PIPELINEDATA,
  '__module__' : 'pipeline_data_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.PB_PipelineData)
  })
_sym_db.RegisterMessage(PB_PipelineData)


# @@protoc_insertion_point(module_scope)
