# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store_configurations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1astore_configurations.proto\x12\x0cstore_config*-\n\x0bProductLine\x12\x08\n\x04\x41UTO\x10\x00\x12\n\n\x06RETAIL\x10\x01\x12\x08\n\x04\x42\x41NK\x10\x02*-\n\x0bProductType\x12\x08\n\x04LITE\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x08\n\x04\x46ULL\x10\x02*D\n\tStoreType\x12\x0b\n\x07REGULAR\x10\x00\x12\x0b\n\x07\x41UTO_4S\x10\x01\x12\x11\n\rSHOPPING_MALL\x10\x02\x12\n\n\x06POP_UP\x10\x03*+\n\x0e\x44\x65oplymentType\x12\x0e\n\nON_PREMISE\x10\x00\x12\t\n\x05\x43LOUD\x10\x01\x62\x06proto3')

_PRODUCTLINE = DESCRIPTOR.enum_types_by_name['ProductLine']
ProductLine = enum_type_wrapper.EnumTypeWrapper(_PRODUCTLINE)
_PRODUCTTYPE = DESCRIPTOR.enum_types_by_name['ProductType']
ProductType = enum_type_wrapper.EnumTypeWrapper(_PRODUCTTYPE)
_STORETYPE = DESCRIPTOR.enum_types_by_name['StoreType']
StoreType = enum_type_wrapper.EnumTypeWrapper(_STORETYPE)
_DEOPLYMENTTYPE = DESCRIPTOR.enum_types_by_name['DeoplymentType']
DeoplymentType = enum_type_wrapper.EnumTypeWrapper(_DEOPLYMENTTYPE)
AUTO = 0
RETAIL = 1
BANK = 2
LITE = 0
MEDIUM = 1
FULL = 2
REGULAR = 0
AUTO_4S = 1
SHOPPING_MALL = 2
POP_UP = 3
ON_PREMISE = 0
CLOUD = 1


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTLINE._serialized_start=44
  _PRODUCTLINE._serialized_end=89
  _PRODUCTTYPE._serialized_start=91
  _PRODUCTTYPE._serialized_end=136
  _STORETYPE._serialized_start=138
  _STORETYPE._serialized_end=206
  _DEOPLYMENTTYPE._serialized_start=208
  _DEOPLYMENTTYPE._serialized_end=251
# @@protoc_insertion_point(module_scope)
