# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracking3d_tracklet_bbox.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracking3d_tracklet_bbox.proto',
  package='test_proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1etracking3d_tracklet_bbox.proto\x12\ntest_proto\"\xcd\x01\n\x19Tracking3dTrackletResults\x12U\n\x11tracking3d_vt_map\x18\x01 \x03(\x0b\x32:.test_proto.Tracking3dTrackletResults.Tracking3dVtMapEntry\x1aY\n\x14Tracking3dVtMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.test_proto.Tracking3dBBoxResults:\x02\x38\x01\"\xa5\x01\n\x15Tracking3dBBoxResults\x12=\n\x06\x62\x62oxes\x18\x01 \x03(\x0b\x32-.test_proto.Tracking3dBBoxResults.BboxesEntry\x1aM\n\x0b\x42\x62oxesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.test_proto.Tracking3dBBoxList:\x02\x38\x01\" \n\x12Tracking3dBBoxList\x12\n\n\x02\x62\x62\x18\x01 \x03(\x05')
)




_TRACKING3DTRACKLETRESULTS_TRACKING3DVTMAPENTRY = _descriptor.Descriptor(
  name='Tracking3dVtMapEntry',
  full_name='test_proto.Tracking3dTrackletResults.Tracking3dVtMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='test_proto.Tracking3dTrackletResults.Tracking3dVtMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='test_proto.Tracking3dTrackletResults.Tracking3dVtMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=252,
)

_TRACKING3DTRACKLETRESULTS = _descriptor.Descriptor(
  name='Tracking3dTrackletResults',
  full_name='test_proto.Tracking3dTrackletResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracking3d_vt_map', full_name='test_proto.Tracking3dTrackletResults.tracking3d_vt_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRACKING3DTRACKLETRESULTS_TRACKING3DVTMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=252,
)


_TRACKING3DBBOXRESULTS_BBOXESENTRY = _descriptor.Descriptor(
  name='BboxesEntry',
  full_name='test_proto.Tracking3dBBoxResults.BboxesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='test_proto.Tracking3dBBoxResults.BboxesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='test_proto.Tracking3dBBoxResults.BboxesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=420,
)

_TRACKING3DBBOXRESULTS = _descriptor.Descriptor(
  name='Tracking3dBBoxResults',
  full_name='test_proto.Tracking3dBBoxResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bboxes', full_name='test_proto.Tracking3dBBoxResults.bboxes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRACKING3DBBOXRESULTS_BBOXESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=420,
)


_TRACKING3DBBOXLIST = _descriptor.Descriptor(
  name='Tracking3dBBoxList',
  full_name='test_proto.Tracking3dBBoxList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bb', full_name='test_proto.Tracking3dBBoxList.bb', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=454,
)

_TRACKING3DTRACKLETRESULTS_TRACKING3DVTMAPENTRY.fields_by_name['value'].message_type = _TRACKING3DBBOXRESULTS
_TRACKING3DTRACKLETRESULTS_TRACKING3DVTMAPENTRY.containing_type = _TRACKING3DTRACKLETRESULTS
_TRACKING3DTRACKLETRESULTS.fields_by_name['tracking3d_vt_map'].message_type = _TRACKING3DTRACKLETRESULTS_TRACKING3DVTMAPENTRY
_TRACKING3DBBOXRESULTS_BBOXESENTRY.fields_by_name['value'].message_type = _TRACKING3DBBOXLIST
_TRACKING3DBBOXRESULTS_BBOXESENTRY.containing_type = _TRACKING3DBBOXRESULTS
_TRACKING3DBBOXRESULTS.fields_by_name['bboxes'].message_type = _TRACKING3DBBOXRESULTS_BBOXESENTRY
DESCRIPTOR.message_types_by_name['Tracking3dTrackletResults'] = _TRACKING3DTRACKLETRESULTS
DESCRIPTOR.message_types_by_name['Tracking3dBBoxResults'] = _TRACKING3DBBOXRESULTS
DESCRIPTOR.message_types_by_name['Tracking3dBBoxList'] = _TRACKING3DBBOXLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tracking3dTrackletResults = _reflection.GeneratedProtocolMessageType('Tracking3dTrackletResults', (_message.Message,), {

  'Tracking3dVtMapEntry' : _reflection.GeneratedProtocolMessageType('Tracking3dVtMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRACKING3DTRACKLETRESULTS_TRACKING3DVTMAPENTRY,
    '__module__' : 'tracking3d_tracklet_bbox_pb2'
    # @@protoc_insertion_point(class_scope:test_proto.Tracking3dTrackletResults.Tracking3dVtMapEntry)
    })
  ,
  'DESCRIPTOR' : _TRACKING3DTRACKLETRESULTS,
  '__module__' : 'tracking3d_tracklet_bbox_pb2'
  # @@protoc_insertion_point(class_scope:test_proto.Tracking3dTrackletResults)
  })
_sym_db.RegisterMessage(Tracking3dTrackletResults)
_sym_db.RegisterMessage(Tracking3dTrackletResults.Tracking3dVtMapEntry)

Tracking3dBBoxResults = _reflection.GeneratedProtocolMessageType('Tracking3dBBoxResults', (_message.Message,), {

  'BboxesEntry' : _reflection.GeneratedProtocolMessageType('BboxesEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRACKING3DBBOXRESULTS_BBOXESENTRY,
    '__module__' : 'tracking3d_tracklet_bbox_pb2'
    # @@protoc_insertion_point(class_scope:test_proto.Tracking3dBBoxResults.BboxesEntry)
    })
  ,
  'DESCRIPTOR' : _TRACKING3DBBOXRESULTS,
  '__module__' : 'tracking3d_tracklet_bbox_pb2'
  # @@protoc_insertion_point(class_scope:test_proto.Tracking3dBBoxResults)
  })
_sym_db.RegisterMessage(Tracking3dBBoxResults)
_sym_db.RegisterMessage(Tracking3dBBoxResults.BboxesEntry)

Tracking3dBBoxList = _reflection.GeneratedProtocolMessageType('Tracking3dBBoxList', (_message.Message,), {
  'DESCRIPTOR' : _TRACKING3DBBOXLIST,
  '__module__' : 'tracking3d_tracklet_bbox_pb2'
  # @@protoc_insertion_point(class_scope:test_proto.Tracking3dBBoxList)
  })
_sym_db.RegisterMessage(Tracking3dBBoxList)


_TRACKING3DTRACKLETRESULTS_TRACKING3DVTMAPENTRY._options = None
_TRACKING3DBBOXRESULTS_BBOXESENTRY._options = None
# @@protoc_insertion_point(module_scope)
