# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trackletmerge_dispatch_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trackletmerge_dispatch_service.proto',
  package='tracking_pipeline.online',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$trackletmerge_dispatch_service.proto\x12\x18tracking_pipeline.online\"7\n\x1cTrackletMergeDispatchRequest\x12\x17\n\x0finput_file_name\x18\x01 \x01(\t\"5\n\x1aTrackletMergeDispatchReply\x12\x17\n\x0finput_file_name\x18\x01 \x01(\t2\xa2\x01\n\x1cTrackletMergeDispatchService\x12\x81\x01\n\x0f\x44oTrackletMerge\x12\x36.tracking_pipeline.online.TrackletMergeDispatchRequest\x1a\x34.tracking_pipeline.online.TrackletMergeDispatchReply\"\x00\x62\x06proto3')
)




_TRACKLETMERGEDISPATCHREQUEST = _descriptor.Descriptor(
  name='TrackletMergeDispatchRequest',
  full_name='tracking_pipeline.online.TrackletMergeDispatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_file_name', full_name='tracking_pipeline.online.TrackletMergeDispatchRequest.input_file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=121,
)


_TRACKLETMERGEDISPATCHREPLY = _descriptor.Descriptor(
  name='TrackletMergeDispatchReply',
  full_name='tracking_pipeline.online.TrackletMergeDispatchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_file_name', full_name='tracking_pipeline.online.TrackletMergeDispatchReply.input_file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['TrackletMergeDispatchRequest'] = _TRACKLETMERGEDISPATCHREQUEST
DESCRIPTOR.message_types_by_name['TrackletMergeDispatchReply'] = _TRACKLETMERGEDISPATCHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackletMergeDispatchRequest = _reflection.GeneratedProtocolMessageType('TrackletMergeDispatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRACKLETMERGEDISPATCHREQUEST,
  '__module__' : 'trackletmerge_dispatch_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.TrackletMergeDispatchRequest)
  })
_sym_db.RegisterMessage(TrackletMergeDispatchRequest)

TrackletMergeDispatchReply = _reflection.GeneratedProtocolMessageType('TrackletMergeDispatchReply', (_message.Message,), {
  'DESCRIPTOR' : _TRACKLETMERGEDISPATCHREPLY,
  '__module__' : 'trackletmerge_dispatch_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.TrackletMergeDispatchReply)
  })
_sym_db.RegisterMessage(TrackletMergeDispatchReply)



_TRACKLETMERGEDISPATCHSERVICE = _descriptor.ServiceDescriptor(
  name='TrackletMergeDispatchService',
  full_name='tracking_pipeline.online.TrackletMergeDispatchService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=179,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoTrackletMerge',
    full_name='tracking_pipeline.online.TrackletMergeDispatchService.DoTrackletMerge',
    index=0,
    containing_service=None,
    input_type=_TRACKLETMERGEDISPATCHREQUEST,
    output_type=_TRACKLETMERGEDISPATCHREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACKLETMERGEDISPATCHSERVICE)

DESCRIPTOR.services_by_name['TrackletMergeDispatchService'] = _TRACKLETMERGEDISPATCHSERVICE

# @@protoc_insertion_point(module_scope)
