# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track_pipeline_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import online_tracking_results_pb2 as online__tracking__results__pb2
import online_event_detection_pb2 as online__event__detection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='track_pipeline_service.proto',
  package='tracking_pipeline.online',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1ctrack_pipeline_service.proto\x12\x18tracking_pipeline.online\x1a\x1donline_tracking_results.proto\x1a\x1conline_event_detection.proto\"\x7f\n\x13tracks_cameraevents\x12\x30\n\x06tracks\x18\x01 \x01(\x0b\x32 .tracking_pipeline.online.Tracks\x12\x36\n\x06\x65vents\x18\x02 \x01(\x0b\x32&.tracking_pipeline.online.CameraEvents\"C\n\x0frealtime_tracks\x12\x30\n\x06tracks\x18\x01 \x01(\x0b\x32 .tracking_pipeline.online.Tracks\"Z\n\x0etracks_results\x12\x30\n\x06tracks\x18\x01 \x01(\x0b\x32 .tracking_pipeline.online.Tracks\x12\x16\n\x0etracks_pb_path\x18\x02 \x01(\t\"B\n\rcrowd_results\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\r\"0\n\x0fPiplineResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa1\x03\n\x13TrackPiplineService\x12\x65\n\x07process\x12-.tracking_pipeline.online.tracks_cameraevents\x1a).tracking_pipeline.online.PiplineResponse\"\x00\x12\x63\n\trtprocess\x12).tracking_pipeline.online.realtime_tracks\x1a).tracking_pipeline.online.PiplineResponse\"\x00\x12_\n\x06savepb\x12(.tracking_pipeline.online.tracks_results\x1a).tracking_pipeline.online.PiplineResponse\"\x00\x12]\n\x05\x63rowd\x12\'.tracking_pipeline.online.crowd_results\x1a).tracking_pipeline.online.PiplineResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[online__tracking__results__pb2.DESCRIPTOR,online__event__detection__pb2.DESCRIPTOR,])




_TRACKS_CAMERAEVENTS = _descriptor.Descriptor(
  name='tracks_cameraevents',
  full_name='tracking_pipeline.online.tracks_cameraevents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='tracking_pipeline.online.tracks_cameraevents.tracks', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='tracking_pipeline.online.tracks_cameraevents.events', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=246,
)


_REALTIME_TRACKS = _descriptor.Descriptor(
  name='realtime_tracks',
  full_name='tracking_pipeline.online.realtime_tracks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='tracking_pipeline.online.realtime_tracks.tracks', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=315,
)


_TRACKS_RESULTS = _descriptor.Descriptor(
  name='tracks_results',
  full_name='tracking_pipeline.online.tracks_results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='tracking_pipeline.online.tracks_results.tracks', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tracks_pb_path', full_name='tracking_pipeline.online.tracks_results.tracks_pb_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=407,
)


_CROWD_RESULTS = _descriptor.Descriptor(
  name='crowd_results',
  full_name='tracking_pipeline.online.crowd_results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='tracking_pipeline.online.crowd_results.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='tracking_pipeline.online.crowd_results.channel', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='tracking_pipeline.online.crowd_results.count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=475,
)


_PIPLINERESPONSE = _descriptor.Descriptor(
  name='PiplineResponse',
  full_name='tracking_pipeline.online.PiplineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='tracking_pipeline.online.PiplineResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='tracking_pipeline.online.PiplineResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=525,
)

_TRACKS_CAMERAEVENTS.fields_by_name['tracks'].message_type = online__tracking__results__pb2._TRACKS
_TRACKS_CAMERAEVENTS.fields_by_name['events'].message_type = online__event__detection__pb2._CAMERAEVENTS
_REALTIME_TRACKS.fields_by_name['tracks'].message_type = online__tracking__results__pb2._TRACKS
_TRACKS_RESULTS.fields_by_name['tracks'].message_type = online__tracking__results__pb2._TRACKS
DESCRIPTOR.message_types_by_name['tracks_cameraevents'] = _TRACKS_CAMERAEVENTS
DESCRIPTOR.message_types_by_name['realtime_tracks'] = _REALTIME_TRACKS
DESCRIPTOR.message_types_by_name['tracks_results'] = _TRACKS_RESULTS
DESCRIPTOR.message_types_by_name['crowd_results'] = _CROWD_RESULTS
DESCRIPTOR.message_types_by_name['PiplineResponse'] = _PIPLINERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

tracks_cameraevents = _reflection.GeneratedProtocolMessageType('tracks_cameraevents', (_message.Message,), {
  'DESCRIPTOR' : _TRACKS_CAMERAEVENTS,
  '__module__' : 'track_pipeline_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.tracks_cameraevents)
  })
_sym_db.RegisterMessage(tracks_cameraevents)

realtime_tracks = _reflection.GeneratedProtocolMessageType('realtime_tracks', (_message.Message,), {
  'DESCRIPTOR' : _REALTIME_TRACKS,
  '__module__' : 'track_pipeline_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.realtime_tracks)
  })
_sym_db.RegisterMessage(realtime_tracks)

tracks_results = _reflection.GeneratedProtocolMessageType('tracks_results', (_message.Message,), {
  'DESCRIPTOR' : _TRACKS_RESULTS,
  '__module__' : 'track_pipeline_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.tracks_results)
  })
_sym_db.RegisterMessage(tracks_results)

crowd_results = _reflection.GeneratedProtocolMessageType('crowd_results', (_message.Message,), {
  'DESCRIPTOR' : _CROWD_RESULTS,
  '__module__' : 'track_pipeline_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.crowd_results)
  })
_sym_db.RegisterMessage(crowd_results)

PiplineResponse = _reflection.GeneratedProtocolMessageType('PiplineResponse', (_message.Message,), {
  'DESCRIPTOR' : _PIPLINERESPONSE,
  '__module__' : 'track_pipeline_service_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.online.PiplineResponse)
  })
_sym_db.RegisterMessage(PiplineResponse)



_TRACKPIPLINESERVICE = _descriptor.ServiceDescriptor(
  name='TrackPiplineService',
  full_name='tracking_pipeline.online.TrackPiplineService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=528,
  serialized_end=945,
  methods=[
  _descriptor.MethodDescriptor(
    name='process',
    full_name='tracking_pipeline.online.TrackPiplineService.process',
    index=0,
    containing_service=None,
    input_type=_TRACKS_CAMERAEVENTS,
    output_type=_PIPLINERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rtprocess',
    full_name='tracking_pipeline.online.TrackPiplineService.rtprocess',
    index=1,
    containing_service=None,
    input_type=_REALTIME_TRACKS,
    output_type=_PIPLINERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='savepb',
    full_name='tracking_pipeline.online.TrackPiplineService.savepb',
    index=2,
    containing_service=None,
    input_type=_TRACKS_RESULTS,
    output_type=_PIPLINERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='crowd',
    full_name='tracking_pipeline.online.TrackPiplineService.crowd',
    index=3,
    containing_service=None,
    input_type=_CROWD_RESULTS,
    output_type=_PIPLINERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACKPIPLINESERVICE)

DESCRIPTOR.services_by_name['TrackPiplineService'] = _TRACKPIPLINESERVICE

# @@protoc_insertion_point(module_scope)
