# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: version.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='version.proto',
  package='tracking_pipeline',
  syntax='proto3',
  serialized_options=_b('Z\006./.gen'),
  serialized_pb=_b('\n\rversion.proto\x12\x11tracking_pipeline\"\xcc\x01\n\rModelVersions\x12\x18\n\x10\x64\x65tector_version\x18\x01 \x01(\t\x12\x1c\n\x14\x66\x61\x63\x65_feature_version\x18\x02 \x01(\t\x12\x1c\n\x14\x66\x61\x63\x65_quality_version\x18\x03 \x01(\t\x12!\n\x19\x62ody_reid_feature_version\x18\x04 \x01(\t\x12!\n\x19head_reid_feature_version\x18\x05 \x01(\t\x12\x1f\n\x17mask_classifier_version\x18\x06 \x01(\t\"\xe8\x01\n\x0eModuleVersions\x12\x16\n\x0e\x64id_sv_version\x18\x01 \x01(\t\x12\x16\n\x0e\x66id_sv_version\x18\x02 \x01(\t\x12\x14\n\x0csvgm_version\x18\x03 \x01(\t\x12\x12\n\nmv_version\x18\x04 \x01(\t\x12\x17\n\x0fmv_link_version\x18\x05 \x01(\t\x12\x18\n\x10god_view_version\x18\x06 \x01(\t\x12\x13\n\x0bnpp_version\x18\x07 \x01(\t\x12\x15\n\revent_version\x18\x08 \x01(\t\x12\x1d\n\x15\x66\x61\x63\x65_pipeline_version\x18\t \x01(\tB\x08Z\x06./.genb\x06proto3')
)




_MODELVERSIONS = _descriptor.Descriptor(
  name='ModelVersions',
  full_name='tracking_pipeline.ModelVersions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detector_version', full_name='tracking_pipeline.ModelVersions.detector_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_feature_version', full_name='tracking_pipeline.ModelVersions.face_feature_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_quality_version', full_name='tracking_pipeline.ModelVersions.face_quality_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body_reid_feature_version', full_name='tracking_pipeline.ModelVersions.body_reid_feature_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='head_reid_feature_version', full_name='tracking_pipeline.ModelVersions.head_reid_feature_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask_classifier_version', full_name='tracking_pipeline.ModelVersions.mask_classifier_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=241,
)


_MODULEVERSIONS = _descriptor.Descriptor(
  name='ModuleVersions',
  full_name='tracking_pipeline.ModuleVersions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='did_sv_version', full_name='tracking_pipeline.ModuleVersions.did_sv_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fid_sv_version', full_name='tracking_pipeline.ModuleVersions.fid_sv_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='svgm_version', full_name='tracking_pipeline.ModuleVersions.svgm_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mv_version', full_name='tracking_pipeline.ModuleVersions.mv_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mv_link_version', full_name='tracking_pipeline.ModuleVersions.mv_link_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='god_view_version', full_name='tracking_pipeline.ModuleVersions.god_view_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='npp_version', full_name='tracking_pipeline.ModuleVersions.npp_version', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_version', full_name='tracking_pipeline.ModuleVersions.event_version', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_pipeline_version', full_name='tracking_pipeline.ModuleVersions.face_pipeline_version', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=476,
)

DESCRIPTOR.message_types_by_name['ModelVersions'] = _MODELVERSIONS
DESCRIPTOR.message_types_by_name['ModuleVersions'] = _MODULEVERSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelVersions = _reflection.GeneratedProtocolMessageType('ModelVersions', (_message.Message,), {
  'DESCRIPTOR' : _MODELVERSIONS,
  '__module__' : 'version_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.ModelVersions)
  })
_sym_db.RegisterMessage(ModelVersions)

ModuleVersions = _reflection.GeneratedProtocolMessageType('ModuleVersions', (_message.Message,), {
  'DESCRIPTOR' : _MODULEVERSIONS,
  '__module__' : 'version_pb2'
  # @@protoc_insertion_point(class_scope:tracking_pipeline.ModuleVersions)
  })
_sym_db.RegisterMessage(ModuleVersions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
