# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtinfos_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vtinfos_map.proto',
  package='mall.vtinfosmap',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11vtinfos_map.proto\x12\x0fmall.vtinfosmap\"\x9b\x01\n\nVTInfosMap\x12\x41\n\x0cvt_infos_map\x18\x01 \x03(\x0b\x32+.mall.vtinfosmap.VTInfosMap.VtInfosMapEntry\x1aJ\n\x0fVtInfosMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.mall.vtinfosmap.VTInfo:\x02\x38\x01\"\x1c\n\x06VTInfo\x12\x12\n\nreid_feats\x18\x04 \x03(\x02\x62\x06proto3')
)




_VTINFOSMAP_VTINFOSMAPENTRY = _descriptor.Descriptor(
  name='VtInfosMapEntry',
  full_name='mall.vtinfosmap.VTInfosMap.VtInfosMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mall.vtinfosmap.VTInfosMap.VtInfosMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mall.vtinfosmap.VTInfosMap.VtInfosMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=194,
)

_VTINFOSMAP = _descriptor.Descriptor(
  name='VTInfosMap',
  full_name='mall.vtinfosmap.VTInfosMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vt_infos_map', full_name='mall.vtinfosmap.VTInfosMap.vt_infos_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VTINFOSMAP_VTINFOSMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=194,
)


_VTINFO = _descriptor.Descriptor(
  name='VTInfo',
  full_name='mall.vtinfosmap.VTInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reid_feats', full_name='mall.vtinfosmap.VTInfo.reid_feats', index=0,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=224,
)

_VTINFOSMAP_VTINFOSMAPENTRY.fields_by_name['value'].message_type = _VTINFO
_VTINFOSMAP_VTINFOSMAPENTRY.containing_type = _VTINFOSMAP
_VTINFOSMAP.fields_by_name['vt_infos_map'].message_type = _VTINFOSMAP_VTINFOSMAPENTRY
DESCRIPTOR.message_types_by_name['VTInfosMap'] = _VTINFOSMAP
DESCRIPTOR.message_types_by_name['VTInfo'] = _VTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VTInfosMap = _reflection.GeneratedProtocolMessageType('VTInfosMap', (_message.Message,), {

  'VtInfosMapEntry' : _reflection.GeneratedProtocolMessageType('VtInfosMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _VTINFOSMAP_VTINFOSMAPENTRY,
    '__module__' : 'vtinfos_map_pb2'
    # @@protoc_insertion_point(class_scope:mall.vtinfosmap.VTInfosMap.VtInfosMapEntry)
    })
  ,
  'DESCRIPTOR' : _VTINFOSMAP,
  '__module__' : 'vtinfos_map_pb2'
  # @@protoc_insertion_point(class_scope:mall.vtinfosmap.VTInfosMap)
  })
_sym_db.RegisterMessage(VTInfosMap)
_sym_db.RegisterMessage(VTInfosMap.VtInfosMapEntry)

VTInfo = _reflection.GeneratedProtocolMessageType('VTInfo', (_message.Message,), {
  'DESCRIPTOR' : _VTINFO,
  '__module__' : 'vtinfos_map_pb2'
  # @@protoc_insertion_point(class_scope:mall.vtinfosmap.VTInfo)
  })
_sym_db.RegisterMessage(VTInfo)


_VTINFOSMAP_VTINFOSMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
